# Generated by Django 5.0.2 on 2025-06-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='Secure Login', max_length=100)),
                ('login_title', models.CharField(default='Welcome Back', max_length=100)),
                ('primary_color', models.CharField(default='#1a237e', max_length=7)),
                ('secondary_color', models.CharField(default='#283593', max_length=7)),
                ('accent_color', models.CharField(default='#3949ab', max_length=7)),
                ('text_color', models.CharField(default='#2b2d42', max_length=7)),
                ('background_color', models.CharField(default='#f8f9fa', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
