# Generated by Django 5.0.2 on 2025-06-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(default='ftp.example.com', max_length=255)),
                ('port', models.IntegerField(default=21)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('remote_directory', models.CharField(default='/uploads', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FTP Configuration',
                'verbose_name_plural': 'FTP Configurations',
            },
        ),
        migrations.CreateModel(
            name='TCPIPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(default='192.168.1.100')),
                ('gateway', models.GenericIPAddressField(default='192.168.1.1')),
                ('subnet_mask', models.GenericIPAddressField(default='255.255.255.0')),
                ('dns', models.GenericIPAddressField(default='8.8.8.8')),
                ('timeout', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TCP/IP Configuration',
                'verbose_name_plural': 'TCP/IP Configurations',
            },
        ),
        migrations.CreateModel(
            name='TimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(choices=[('UTC', 'UTC'), ('EST', 'EST'), ('PST', 'PST')], default='UTC', max_length=10)),
                ('date_format', models.CharField(choices=[('YYYY-MM-DD', 'YYYY-MM-DD'), ('DD-MM-YYYY', 'DD-MM-YYYY'), ('MM-DD-YYYY', 'MM-DD-YYYY')], default='YYYY-MM-DD', max_length=10)),
                ('time_format', models.CharField(choices=[('24h', '24-hour'), ('12h', '12-hour')], default='24h', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Time Configuration',
                'verbose_name_plural': 'Time Configurations',
            },
        ),
    ]
