# Generated by Django 5.0.2 on 2025-06-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_radarobjectdetection'),
    ]

    operations = [
        migrations.AddField(
            model_name='radarobjectdetection',
            name='anpr_detected',
            field=models.BooleanField(default=False, help_text='Whether a license plate was detected'),
        ),
        migrations.AddField(
            model_name='radarobjectdetection',
            name='license_plate',
            field=models.CharField(blank=True, help_text='Detected license plate number', max_length=20, null=True),
        ),
    ]
