# Generated by Django 5.0.2 on 2025-06-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ftpconfig_tcpipconfig_timeconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name to identify this radar', max_length=100)),
                ('port', models.CharField(help_text='Serial port (e.g., COM1, /dev/ttyUSB0)', max_length=50)),
                ('baud_rate', models.IntegerField(choices=[(9600, '9600'), (19200, '19200'), (38400, '38400'), (57600, '57600'), (115200, '115200')], default=9600)),
                ('data_bits', models.IntegerField(choices=[(7, '7'), (8, '8')], default=8)),
                ('parity', models.CharField(choices=[('N', 'None'), ('E', 'Even'), ('O', 'Odd')], default='N', max_length=1)),
                ('stop_bits', models.IntegerField(choices=[(1, '1'), (2, '2')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Radar Configuration',
                'verbose_name_plural': 'Radar Configurations',
                'ordering': ['-created_at'],
            },
        ),
    ]
