# Generated by Django 5.0.2 on 2025-06-16 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_radarobjectdetection_anpr_detected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANPRConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(default='192.168.1.200', help_text='IP address of the ANPR server')),
                ('port', models.IntegerField(default=8080, help_text='Port number for ANPR server communication', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('polling_interval', models.IntegerField(default=1000, help_text='Interval between ANPR readings in milliseconds', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(5000)])),
                ('timeout', models.IntegerField(default=5, help_text='Connection timeout in seconds', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('endpoint', models.CharField(default='/api/plate', help_text='API endpoint for ANPR data', max_length=255)),
                ('api_key', models.CharField(blank=True, help_text='API key for authentication (if required)', max_length=255)),
                ('enable_continuous_reading', models.BooleanField(default=True, help_text='Enable continuous reading mode')),
                ('enable_logging', models.BooleanField(default=True, help_text='Enable ANPR logging')),
                ('log_path', models.CharField(default='logs/anpr', help_text='Path where ANPR logs will be stored', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ANPR Configuration',
                'verbose_name_plural': 'ANPR Configurations',
            },
        ),
    ]
