# Generated by Django 5.0.2 on 2025-06-11 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_radarconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_email', models.EmailField(help_text='Primary email address for notifications', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', help_text='How often to send notifications', max_length=10)),
                ('cc_emails', models.TextField(blank=True, help_text='Comma-separated list of CC email addresses')),
                ('smtp_server', models.CharField(help_text='SMTP server address', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP server port', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('smtp_username', models.CharField(help_text='SMTP username', max_length=255)),
                ('smtp_password', models.CharField(help_text='SMTP password', max_length=255)),
                ('enable_notifications', models.BooleanField(default=True, help_text='Enable/disable email notifications')),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS for SMTP connection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
    ]
