# Generated by Django 5.0.2 on 2025-06-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_notificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='days_of_week',
            field=models.CharField(blank=True, help_text='Comma-separated days of the week (e.g., Monday,Tuesday,Friday)', max_length=100),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notification_times',
            field=models.CharField(blank=True, help_text='Comma-separated times in HH:MM format (e.g., 08:00,14:00)', max_length=100),
        ),
    ]
