# Generated by Django 5.0.2 on 2025-06-16 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_anprconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='anprconfig',
            name='radar',
            field=models.ForeignKey(blank=True, help_text='Associated radar for this ANPR configuration', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anpr_configs', to='app.radarconfig'),
        ),
    ]
