# Generated by Django 5.0.2 on 2025-06-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_notificationsettings_days_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radarconfig',
            name='port',
            field=models.CharField(help_text='Serial port (e.g., COM1, /dev/ttyUSB0)', max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='radarconfig',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_radar_name'),
        ),
    ]
