# Generated by Django 5.0.2 on 2025-06-11 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_radarconfig_port_radarconfig_unique_radar_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('disk_used_percent', models.FloatField(help_text='Disk usage percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ram_used_percent', models.FloatField(help_text='RAM usage percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cpu_temperature', models.FloatField(blank=True, help_text='CPU temperature in Celsius', null=True)),
                ('uptime_seconds', models.IntegerField(help_text='System uptime in seconds')),
            ],
            options={
                'verbose_name': 'System Metric',
                'verbose_name_plural': 'System Metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='app_systemm_timesta_cdddb8_idx')],
            },
        ),
    ]
