# Generated by Django 5.0.2 on 2025-06-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_email_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_objects', models.IntegerField(default=0, help_text='Total number of objects detected')),
                ('active_radars', models.IntegerField(default=0, help_text='Number of active radars')),
                ('last_detection', models.DateTimeField(blank=True, help_text='Time of the last detection', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Summary Statistics',
                'verbose_name_plural': 'Summary Statistics',
                'ordering': ['-timestamp'],
            },
        ),
    ]
