# Generated by Django 5.0.2 on 2025-06-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_summarystats'),
    ]

    operations = [
        migrations.AddField(
            model_name='radarconfig',
            name='direction',
            field=models.CharField(choices=[('+', 'Towards Village'), ('-', 'Towards Town')], default='+', help_text="Direction of the radar: '+' for Towards Village, '-' for Towards Town", max_length=1),
        ),
    ]
