# Generated by Django 5.0.2 on 2025-06-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_systemmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='radarconfig',
            name='update_interval',
            field=models.IntegerField(default=100, help_text='Update interval in milliseconds (min: 50ms, max: 1000ms)'),
        ),
    ]
