# Generated by Django 5.0.2 on 2025-06-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_radarconfig_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='radarconfig',
            name='direction_negative_name',
            field=models.CharField(default='Towards Town', help_text="Name for the negative ('-') direction", max_length=100),
        ),
        migrations.AddField(
            model_name='radarconfig',
            name='direction_positive_name',
            field=models.CharField(default='Towards Village', help_text="Name for the positive ('+') direction", max_length=100),
        ),
        migrations.AlterField(
            model_name='radarconfig',
            name='direction',
            field=models.CharField(choices=[('+', 'Positive'), ('-', 'Negative')], default='+', help_text="Direction of the radar: '+' for positive, '-' for negative", max_length=1),
        ),
    ]
