# Generated by Django 5.0.2 on 2025-06-12 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='radarconfig',
            name='data_storage_path',
            field=models.CharField(default='data', help_text='Path to store radar data files', max_length=255),
        ),
        migrations.AddField(
            model_name='radarconfig',
            name='file_save_interval',
            field=models.IntegerField(default=5, help_text='Interval for saving data to files in minutes (min: 1min, max: 60min)'),
        ),
        migrations.CreateModel(
            name='RadarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('range', models.FloatField(blank=True, help_text='Range measurement in meters', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed measurement in m/s', null=True)),
                ('direction', models.FloatField(blank=True, help_text='Direction in degrees', null=True)),
                ('raw_data', models.TextField(blank=True, help_text='Raw data if parsing failed', null=True)),
                ('status', models.CharField(default='success', help_text='Status of the reading', max_length=20)),
                ('connection_status', models.CharField(default='connected', help_text='Connection status', max_length=20)),
                ('radar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='app.radarconfig')),
            ],
            options={
                'verbose_name': 'Radar Data',
                'verbose_name_plural': 'Radar Data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['radar', 'timestamp'], name='app_radarda_radar_i_2c53e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='RadarDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Name of the saved file', max_length=255)),
                ('file_path', models.CharField(help_text='Full path to the saved file', max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the file was saved')),
                ('record_count', models.IntegerField(help_text='Number of records in the file')),
                ('file_size', models.BigIntegerField(help_text='Size of the file in bytes')),
                ('is_valid', models.BooleanField(default=True, help_text='Whether the file is valid and complete')),
                ('radar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='app.radarconfig')),
            ],
            options={
                'verbose_name': 'Radar Data File',
                'verbose_name_plural': 'Radar Data Files',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['radar', 'timestamp'], name='app_radarda_radar_i_67ab85_idx')],
            },
        ),
    ]
