# Generated by Django 5.0.2 on 2025-06-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_radarconfig_direction_negative_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radarconfig',
            name='direction',
        ),
        migrations.AlterField(
            model_name='radarconfig',
            name='direction_negative_name',
            field=models.CharField(default='Towards Town', help_text='Name for the negative direction', max_length=100),
        ),
        migrations.AlterField(
            model_name='radarconfig',
            name='direction_positive_name',
            field=models.CharField(default='Towards Village', help_text='Name for the positive direction', max_length=100),
        ),
    ]
