# Generated by Django 5.0.2 on 2025-06-12 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_radarconfig_data_storage_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadarDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Name of the saved file', max_length=255)),
                ('file_path', models.CharField(help_text='Full path to the saved file', max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the file was saved')),
                ('record_count', models.IntegerField(help_text='Number of records in the file')),
                ('file_size', models.BigIntegerField(help_text='Size of the file in bytes')),
                ('is_valid', models.BooleanField(default=True, help_text='Whether the file is valid and complete')),
                ('radar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='app.radarconfig')),
            ],
            options={
                'verbose_name': 'Radar Data File',
                'verbose_name_plural': 'Radar Data Files',
                'ordering': ['-timestamp'],
                'indexes': [
                    models.Index(fields=['radar', 'timestamp'], name='app_radarda_radar_i_67ab85_idx'),
                ],
            },
        ),
    ] 