# Generated by Django 5.0.2 on 2025-07-20 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_radardatafile_email_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imr_ad', models.CharField(help_text='System identifier (e.g., IMR_KD-BEKO)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='System name (e.g., K Dubči)', max_length=100)),
                ('route', models.CharField(blank=True, help_text='Route information', max_length=255)),
                ('datetime', models.DateTimeField(help_text='System datetime')),
                ('lat', models.DecimalField(decimal_places=8, help_text='Latitude coordinate', max_digits=10)),
                ('lon', models.DecimalField(decimal_places=8, help_text='Longitude coordinate', max_digits=11)),
                ('detections', models.IntegerField(default=0, help_text='Total detections')),
                ('detections_ANPR', models.IntegerField(default=0, help_text='Total ANPR detections')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this system is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('radar', models.ForeignKey(help_text='Associated radar for this system', on_delete=django.db.models.deletion.CASCADE, related_name='system_details', to='app.radarconfig')),
            ],
            options={
                'verbose_name': 'System Detail',
                'verbose_name_plural': 'System Details',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='SystemDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_id', models.CharField(help_text='Direction identifier (e.g., IMR_KD-BE)', max_length=50)),
                ('name', models.CharField(help_text='Direction name (e.g., K Běchovicům)', max_length=100)),
                ('detections', models.IntegerField(default=0, help_text='Total detections for this direction')),
                ('detections_ANPR', models.IntegerField(default=0, help_text='ANPR detections for this direction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='app.systemdetails')),
            ],
            options={
                'verbose_name': 'System Direction',
                'verbose_name_plural': 'System Directions',
                'ordering': ['direction_id'],
                'unique_together': {('system_detail', 'direction_id')},
            },
        ),
    ]
