# Generated by Django 5.0.2 on 2025-06-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_add_radardatafile_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_usage', models.FloatField()),
                ('ram_usage', models.FloatField()),
                ('cpu_temp', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Info',
                'verbose_name_plural': 'System Info',
                'ordering': ['-timestamp'],
            },
        ),
    ]
