# Generated by Django 5.0.2 on 2025-07-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_systemdetails_systemdirection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemdetails',
            name='detections',
        ),
        migrations.RemoveField(
            model_name='systemdetails',
            name='detections_ANPR',
        ),
        migrations.AddField(
            model_name='radarconfig',
            name='direction_id_negative',
            field=models.CharField(blank=True, help_text='Negative direction ID (e.g., IMR_KD-KO)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='radarconfig',
            name='direction_id_positive',
            field=models.CharField(blank=True, help_text='Positive direction ID (e.g., IMR_KD-BE)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='radarconfig',
            name='imr_ad',
            field=models.CharField(blank=True, help_text='IMR_AD identifier (e.g., IMR_KD-BEKO)', max_length=50, null=True),
        ),
    ]
