# Generated by Django 5.0.2 on 2025-07-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_systemdetails_detections_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemDirection',
        ),
        migrations.DeleteModel(
            name='SystemDetails',
        ),
    ]
