# Generated by Django 5.0.2 on 2025-07-20 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_system_details_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(default='192.168.1.222', help_text='IP address of the display device')),
                ('port', models.IntegerField(default=8080, help_text='Port number for display communication', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('font_size', models.IntegerField(default=16, help_text='Font size for display text', validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(72)])),
                ('effect_type', models.CharField(choices=[('draw', 'Draw'), ('scroll', 'Scroll'), ('flash', 'Flash'), ('fade', 'Fade')], default='draw', help_text='Visual effect for text display', max_length=20)),
                ('justify', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='right', help_text='Text alignment on display', max_length=10)),
                ('test_message', models.CharField(blank=True, help_text='Test message for display testing', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Display Configuration',
                'verbose_name_plural': 'Display Configurations',
            },
        ),
    ]
