# Generated by Django 5.0.2 on 2025-07-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_displayconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='radarobjectdetection',
            name='anpr_confidence',
            field=models.IntegerField(blank=True, help_text='Confidence of ANPR detection', null=True),
        ),
        migrations.AddField(
            model_name='radarobjectdetection',
            name='anpr_device_id',
            field=models.CharField(blank=True, help_text='Device ID of ANPR camera', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='radarobjectdetection',
            name='anpr_image_url',
            field=models.URLField(blank=True, help_text='URL of ANPR image', null=True),
        ),
        migrations.AddField(
            model_name='radarobjectdetection',
            name='anpr_record_id',
            field=models.CharField(blank=True, help_text='Record ID of ANPR event', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='radarobjectdetection',
            name='anpr_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp of ANPR event (picTime)', null=True),
        ),
    ]
