# Generated by Django 5.0.2 on 2025-07-24 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_radarobjectdetection_anpr_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anprconfig',
            name='matching_window_seconds',
            field=models.IntegerField(default=2, help_text='Time window (seconds) to match ANPR to radar detections', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='anprconfig',
            name='protocol',
            field=models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], default='http', help_text='Protocol to use for ANPR camera callback URL', max_length=10),
        ),
    ]
