# Generated by Django 5.0.2 on 2025-08-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_anprconfig_matching_window_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayconfig',
            name='color',
            field=models.CharField(choices=[('white', 'White'), ('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('orange', 'Orange'), ('purple', 'Purple')], default='white', help_text='Text color for display', max_length=20),
        ),
    ]
