# Generated by Django 5.0.2 on 2025-10-07 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_displayconfig_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Camera name', max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='Camera IP address')),
                ('port', models.IntegerField(default=5000, help_text='Camera port')),
                ('username', models.CharField(default='admin', help_text='Camera username', max_length=50)),
                ('password', models.CharField(help_text='Camera password', max_length=100)),
                ('protocol', models.CharField(default='VIID_2017', help_text='Protocol version', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is camera active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camera Configuration',
                'verbose_name_plural': 'Camera Configurations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='radarconfig',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude coordinate', null=True),
        ),
        migrations.AddField(
            model_name='radarconfig',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude coordinate', null=True),
        ),
        migrations.AddField(
            model_name='radarconfig',
            name='route',
            field=models.CharField(blank=True, help_text='Route identifier', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='summarystats',
            name='active_cameras',
            field=models.IntegerField(default=0, help_text='Number of active cameras'),
        ),
        migrations.CreateModel(
            name='CameraDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(help_text='License plate number', max_length=20)),
                ('confidence', models.FloatField(help_text='Detection confidence (0-100)')),
                ('speed', models.FloatField(blank=True, help_text='Vehicle speed in km/h', null=True)),
                ('direction', models.CharField(blank=True, help_text='Vehicle direction', max_length=50)),
                ('vehicle_type', models.CharField(default='Motor Vehicle', help_text='Type of vehicle', max_length=50)),
                ('timestamp', models.DateTimeField(help_text='Detection timestamp')),
                ('raw_data', models.TextField(blank=True, help_text='Raw detection data')),
                ('data_format', models.CharField(default='unknown', help_text='Data format (xml, json, text)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='app.cameraconfig')),
            ],
            options={
                'verbose_name': 'Camera Detection',
                'verbose_name_plural': 'Camera Detections',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['camera', 'timestamp'], name='app_camerad_camera__2e6535_idx'), models.Index(fields=['plate_number'], name='app_camerad_plate_n_39e303_idx')],
            },
        ),
    ]
